package cn.net.lyta.openlyta.entity;

import java.io.Serializable;
import java.util.Date;

public class Scenic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_id
     *
     * @mbg.generated
     */
    private Long scenicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_type
     *
     * @mbg.generated
     */
    private String scenicType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.rank
     *
     * @mbg.generated
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_name
     *
     * @mbg.generated
     */
    private String scenicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_img_path
     *
     * @mbg.generated
     */
    private String scenicImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_content
     *
     * @mbg.generated
     */
    private String scenicContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.open_time
     *
     * @mbg.generated
     */
    private String openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_address
     *
     * @mbg.generated
     */
    private String scenicAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.creat_time
     *
     * @mbg.generated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scenic
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_id
     *
     * @return the value of scenic.scenic_id
     *
     * @mbg.generated
     */
    public Long getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_id
     *
     * @param scenicId the value for scenic.scenic_id
     *
     * @mbg.generated
     */
    public void setScenicId(Long scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_type
     *
     * @return the value of scenic.scenic_type
     *
     * @mbg.generated
     */
    public String getScenicType() {
        return scenicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_type
     *
     * @param scenicType the value for scenic.scenic_type
     *
     * @mbg.generated
     */
    public void setScenicType(String scenicType) {
        this.scenicType = scenicType == null ? null : scenicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.rank
     *
     * @return the value of scenic.rank
     *
     * @mbg.generated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.rank
     *
     * @param rank the value for scenic.rank
     *
     * @mbg.generated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_name
     *
     * @return the value of scenic.scenic_name
     *
     * @mbg.generated
     */
    public String getScenicName() {
        return scenicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_name
     *
     * @param scenicName the value for scenic.scenic_name
     *
     * @mbg.generated
     */
    public void setScenicName(String scenicName) {
        this.scenicName = scenicName == null ? null : scenicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_img_path
     *
     * @return the value of scenic.scenic_img_path
     *
     * @mbg.generated
     */
    public String getScenicImgPath() {
        return scenicImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_img_path
     *
     * @param scenicImgPath the value for scenic.scenic_img_path
     *
     * @mbg.generated
     */
    public void setScenicImgPath(String scenicImgPath) {
        this.scenicImgPath = scenicImgPath == null ? null : scenicImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_content
     *
     * @return the value of scenic.scenic_content
     *
     * @mbg.generated
     */
    public String getScenicContent() {
        return scenicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_content
     *
     * @param scenicContent the value for scenic.scenic_content
     *
     * @mbg.generated
     */
    public void setScenicContent(String scenicContent) {
        this.scenicContent = scenicContent == null ? null : scenicContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.price
     *
     * @return the value of scenic.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.price
     *
     * @param price the value for scenic.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.open_time
     *
     * @return the value of scenic.open_time
     *
     * @mbg.generated
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.open_time
     *
     * @param openTime the value for scenic.open_time
     *
     * @mbg.generated
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_address
     *
     * @return the value of scenic.scenic_address
     *
     * @mbg.generated
     */
    public String getScenicAddress() {
        return scenicAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_address
     *
     * @param scenicAddress the value for scenic.scenic_address
     *
     * @mbg.generated
     */
    public void setScenicAddress(String scenicAddress) {
        this.scenicAddress = scenicAddress == null ? null : scenicAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.creat_time
     *
     * @return the value of scenic.creat_time
     *
     * @mbg.generated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.creat_time
     *
     * @param creatTime the value for scenic.creat_time
     *
     * @mbg.generated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scenicId=").append(scenicId);
        sb.append(", scenicType=").append(scenicType);
        sb.append(", rank=").append(rank);
        sb.append(", scenicName=").append(scenicName);
        sb.append(", scenicImgPath=").append(scenicImgPath);
        sb.append(", scenicContent=").append(scenicContent);
        sb.append(", price=").append(price);
        sb.append(", openTime=").append(openTime);
        sb.append(", scenicAddress=").append(scenicAddress);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}