package cn.net.lyta.openlyta.dao;

import cn.net.lyta.openlyta.entity.Scenic;
import java.util.List;

public interface ScenicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long scenicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    int insert(Scenic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    Scenic selectByPrimaryKey(Long scenicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    List<Scenic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scenic record);
}